#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo -e "\n🎡🧬 Trying to generate .sample.env file..."
helper gen-env -s

# if [ $? -eq 0 ]; then
#   echo ".sample.env file generated."
# fi
echo -e "\n➕🧋 Adding all files to the git stage"
git add .

echo -e "\n🖇️📙 Linting and fixing the code issues"
npx lint-staged

echo -e "\n🧪🍷 Tests are comming soon here!"