#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "\n🎡🧬Trying to generating .sample.env file..."
helper gen-env -s

# if [ $? -eq 0 ]; then
#   echo ".sample.env file generated."
# fi
echo "\n➕🧋Adding all files to the git stage"
git add .

echo "\n🖇️📙Linting and fixing the code issues"
npx lint-staged

echo "\n🧪🍷Tests are comming soon here!"